services:
  beammp_chathook:
    build:
      context: ..
      dockerfile: .docker/Dockerfile

    container_name: "beammp.chathook"
    ports:
      - ${EXPOSE_TO_NETWORK}:${UDP_PORT}:30813/udp
    network_mode: bridge
    restart: unless-stopped
    environment:
      WEBHOOK_URL: ${WEBHOOK_URL}
      UDP_PORT: 30813
      AVATAR_URL: ${AVATAR_URL}

    deploy:
      resources:
        limits:
          memory: 1G
